# Generated by Django 3.0 on 2020-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0002_film_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='H',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='L',
            field=models.IntegerField(default=0),
        ),
    ]
