# Generated by Django 3.0 on 2020-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0003_auto_20200720_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='H',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='L',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
