# Generated by Django 3.0 on 2020-07-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0054_reference_available_for_workshop'),
        ('workshopworkspace', '0004_auto_20200720_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='reference',
        ),
        migrations.AddField(
            model_name='package',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Reference'),
        ),
    ]
