# Generated by Django 3.0 on 2020-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0005_auto_20200720_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopjob',
            name='employee',
        ),
    ]
