# Generated by Django 3.0 on 2020-07-21 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0059_auto_20200721_1803'),
        ('workshopworkspace', '0007_package_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_waste', models.DateField(auto_now=True, null=True)),
                ('qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.WasteCategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopworkspace.WasteWorkshop'),
        ),
    ]
