# Generated by Django 3.0 on 2020-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0008_auto_20200721_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='waste',
        ),
        migrations.AddField(
            model_name='package',
            name='waste',
            field=models.ManyToManyField(blank=True, to='workshopworkspace.WasteWorkshop'),
        ),
    ]
