# Generated by Django 3.0 on 2020-07-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0011_auto_20200722_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutplan',
            name='nb_of_ref_possible',
            field=models.IntegerField(default=0),
        ),
    ]
