# Generated by Django 3.0 on 2020-07-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0012_auto_20200722_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfilm',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
