# Generated by Django 3.0 on 2020-07-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0060_referenceapplied_had_stock_update'),
        ('workshopworkspace', '0015_auto_20200722_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('date_record', models.DateField(blank=True, null=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistoryWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference')),
                ('stock', models.ManyToManyField(to='workshopworkspace.StockWorkshop')),
            ],
        ),
        migrations.CreateModel(
            name='FilmReel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshopworkspace.Film')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='film_reel_nb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopworkspace.FilmReel'),
        ),
    ]
