# Generated by Django 3.0 on 2020-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0016_auto_20200729_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='film_reel_nb',
        ),
        migrations.AddField(
            model_name='package',
            name='film_reel_nb',
            field=models.ManyToManyField(to='workshopworkspace.FilmReel'),
        ),
    ]
