# Generated by Django 3.0 on 2020-07-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0018_remove_package_film_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='film_reel_nb',
            new_name='film_reel',
        ),
    ]
