# Generated by Django 3.0 on 2020-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0020_auto_20200730_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available_at_office',
            field=models.BooleanField(default=True),
        ),
    ]
