# Generated by Django 3.0 on 2020-08-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0073_auto_20200803_1548'),
        ('workshopworkspace', '0021_package_available_at_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='references_applied',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.ReferenceApplied'),
        ),
    ]
