# Generated by Django 3.0 on 2020-08-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0022_auto_20200803_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
