# Generated by Django 3.0 on 2020-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0023_auto_20200803_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship_date_created', models.DateField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
