# Generated by Django 3.0 on 2020-08-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0079_qualityfeedback_qty_applied'),
        ('workshopworkspace', '0024_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfilmhistory',
            name='qty_car_single',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.Quantity'),
        ),
        migrations.AddField(
            model_name='stockfilmhistory',
            name='qty_per_train',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockhistoryworkshop',
            name='qty_car_single',
            field=models.ManyToManyField(to='teamleaderworkspace.Quantity'),
        ),
        migrations.AddField(
            model_name='stockhistoryworkshop',
            name='qty_per_train',
            field=models.IntegerField(default=0),
        ),
    ]
