# Generated by Django 3.0 on 2020-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0079_qualityfeedback_qty_applied'),
        ('workshopworkspace', '0025_auto_20200805_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistoryworkshop',
            name='qty_car_single',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.Quantity'),
        ),
    ]
