# Generated by Django 3.0 on 2020-08-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0026_auto_20200805_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockfilmhistory',
            name='qty_car_single',
        ),
    ]
