# Generated by Django 3.0 on 2020-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0027_remove_stockfilmhistory_qty_car_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfilmhistory',
            name='qty_per_train',
            field=models.FloatField(default=0),
        ),
    ]
