# Generated by Django 3.0 on 2020-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopworkspace', '0029_stockfilmhistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockfilmhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='photographic-film.png', upload_to='film_pics'),
        ),
    ]
