# Generated by Django 3.0 on 2020-09-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0107_quality_waste'),
        ('users', '0003_profile_salary'),
        ('workshopworkspace', '0032_auto_20200915_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteworkshop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.WasteCategory'),
        ),
        migrations.AlterField(
            model_name='wasteworkshop',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='wasteworkshop',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Reference'),
        ),
    ]
