# Generated by Django 3.0 on 2020-05-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('MA', 'Manager'), ('TL', 'Team leader'), ('TN', 'Technician'), ('WS', 'Workshop'), ('CL', 'Client')], default='TN', max_length=2),
        ),
    ]
