# Generated by Django 3.0 on 2020-09-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
