# Generated by Django 3.0.5 on 2020-05-23 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='cars',
            field=models.ManyToManyField(to='teamleaderworkspace.Car'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Part'),
        ),
        migrations.DeleteModel(
            name='UserReference',
        ),
    ]
