# Generated by Django 3.0 on 2020-05-28 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0003_auto_20200528_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsToCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Car')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Part')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Train')),
            ],
        ),
         migrations.RemoveField(
            model_name='train',
            name='parts',
        ),

        migrations.AddField(
            model_name='train',
            name='parts',
            field=models.ManyToManyField(through='teamleaderworkspace.PartsToCar', to='teamleaderworkspace.Part'),
        ),

    ]
