# Generated by Django 3.0 on 2020-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0008_auto_20200609_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refstocar',
            name='car',
        ),
        migrations.RemoveField(
            model_name='refstocar',
            name='part',
        ),
        migrations.RemoveField(
            model_name='refstocar',
            name='references',
        ),
        migrations.RemoveField(
            model_name='refstocar',
            name='train',
        ),
        migrations.RemoveField(
            model_name='part',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='part',
            field=models.ManyToManyField(to='teamleaderworkspace.Part'),
        ),
        migrations.DeleteModel(
            name='PartsToCar',
        ),
        migrations.DeleteModel(
            name='RefsToCar',
        ),
    ]
