# Generated by Django 3.0 on 2020-06-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0009_auto_20200611_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Car')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Part')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Train')),
            ],
        ),
    ]
