# Generated by Django 3.0 on 2020-06-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0010_partlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Tech')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.PartLinks')),
            ],
        ),
    ]
