# Generated by Django 3.0 on 2020-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0011_teamlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlinks',
            name='work',
        ),
        migrations.AddField(
            model_name='teamlinks',
            name='work',
            field=models.ManyToManyField(to='teamleaderworkspace.PartLinks'),
        ),
    ]
