# Generated by Django 3.0 on 2020-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0012_auto_20200611_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donetoday',
            name='team',
        ),
        migrations.RemoveField(
            model_name='donetoday',
            name='train',
        ),
        migrations.AddField(
            model_name='donetoday',
            name='work',
            field=models.ManyToManyField(to='teamleaderworkspace.PartLinks'),
        ),
        migrations.AddField(
            model_name='partlinks',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamlinks',
            name='last_work',
            field=models.DateField(auto_now=True),
        ),
    ]
