# Generated by Django 3.0 on 2020-06-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0013_auto_20200611_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partlinks',
            options={'ordering': ['train']},
        ),
        migrations.RemoveField(
            model_name='appliedby',
            name='DoneToday',
        ),
        migrations.AddField(
            model_name='appliedby',
            name='date_worked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donetoday',
            name='references_applied',
            field=models.ManyToManyField(to='teamleaderworkspace.AppliedBy'),
        ),
        migrations.AlterField(
            model_name='partlinks',
            name='date_started',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='date_started',
            field=models.DateField(auto_now_add=True),
        ),
    ]
