# Generated by Django 3.0 on 2020-06-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0014_auto_20200611_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedby',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.TeamLinks'),
        ),
    ]
