# Generated by Django 3.0 on 2020-06-17 11:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0016_auto_20200613_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamlinks',
            options={'ordering': ['tech']},
        ),
        migrations.AlterModelManagers(
            name='teamlinks',
            managers=[
                ('work_info', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='partlinks',
            name='last_work',
            field=models.DateField(auto_now=True),
        ),
    ]
