# Generated by Django 3.0 on 2020-06-24 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamleaderworkspace', '0018_auto_20200625_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoneToday',
            new_name='WorkDone',
        ),
    ]
