# Generated by Django 3.0 on 2020-07-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0031_auto_20200704_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceapplied',
            name='reference',
        ),
    ]
