# Generated by Django 3.0 on 2020-07-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0032_remove_referenceapplied_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceapplied',
            name='tech',
        ),
    ]
