# Generated by Django 3.0 on 2020-07-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0033_remove_referenceapplied_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceapplied',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference'),
            preserve_default=False,
        ),
    ]
