# Generated by Django 3.0 on 2020-07-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0034_referenceapplied_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceapplied',
            name='reference',
        ),
    ]
