# Generated by Django 3.0 on 2020-07-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0035_remove_referenceapplied_reference'),
    ]

    operations = [
        
    ]
