# Generated by Django 3.0 on 2020-07-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0038_auto_20200704_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceapplied',
            name='date_work',
        ),
        migrations.RemoveField(
            model_name='referenceapplied',
            name='job',
        ),
        migrations.RemoveField(
            model_name='referenceapplied',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='referenceapplied',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='referenceapplied',
            name='waste',
        ),
    ]
