# Generated by Django 3.0 on 2020-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0040_auto_20200704_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceapplied',
            name='waste',
        ),
        migrations.AddField(
            model_name='referenceapplied',
            name='waste',
            field=models.ManyToManyField(blank=True, null=True, to='teamleaderworkspace.Waste'),
        ),
    ]
