# Generated by Django 3.0 on 2020-07-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0041_auto_20200705_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty_needed', models.IntegerField()),
                ('car_type', models.CharField(choices=[('1', 'TC'), ('2', 'M')], max_length=2)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reference',
            name='possible_locations',
        ),
        migrations.RemoveField(
            model_name='referenceapplied',
            name='locations',
        ),
        migrations.AddField(
            model_name='reference',
            name='possible_waste',
            field=models.ManyToManyField(to='teamleaderworkspace.WasteCategory'),
        ),
        migrations.AddField(
            model_name='reference',
            name='possible_locations',
            field=models.ManyToManyField(blank=True, null=True, to='teamleaderworkspace.Location'),
        ),
        migrations.AddField(
            model_name='referenceapplied',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='teamleaderworkspace.Location'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.WasteCategory'),
        ),
    ]
