# Generated by Django 3.0 on 2020-07-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0043_auto_20200705_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='qty_needed',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='qty_Mcar',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='qty_TCcar',
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('TC', 'TC'), ('M', 'M')], max_length=2)),
                ('qty_needed', models.IntegerField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference')),
            ],
        ),
    ]
