# Generated by Django 3.0 on 2020-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0044_auto_20200705_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='referenceapplied',
            name='last_work',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
