# Generated by Django 3.0 on 2020-07-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0046_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Reference')),
            ],
        ),
    ]
