# Generated by Django 3.0 on 2020-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0047_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_update',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_record',
            field=models.DateField(blank=True, null=True),
        ),
    ]
