# Generated by Django 3.0 on 2020-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0049_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
