# Generated by Django 3.0.5 on 2020-07-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamleaderworkspace', '0050_auto_20200711_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='part',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='user',
        ),
        migrations.RemoveField(
            model_name='train',
            name='selected',
        ),
        migrations.AddField(
            model_name='car',
            name='selectedby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='part',
            name='selectedby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tech',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='tech',
            name='selectedby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='train',
            name='selectedby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
