# Generated by Django 3.0.5 on 2020-07-14 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0052_waste_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='job_waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teamleaderworkspace.Job'),
        ),
    ]
