# Generated by Django 3.0 on 2020-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0054_reference_available_for_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='available_for_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
