# Generated by Django 3.0 on 2020-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0056_waste_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='date_waste',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='waste',
            name='workshop',
        ),
        migrations.AddField(
            model_name='waste',
            name='workshop',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile'),
        ),
    ]
