# Generated by Django 3.0 on 2020-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0057_auto_20200720_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='workshop',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
