# Generated by Django 3.0 on 2020-07-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0058_auto_20200720_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='date_waste',
        ),
        migrations.RemoveField(
            model_name='waste',
            name='workshop',
        ),
    ]
