# Generated by Django 3.0 on 2020-07-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0060_referenceapplied_had_stock_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
