# Generated by Django 3.0 on 2020-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0061_reference_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='qty_car_single',
            field=models.ManyToManyField(to='teamleaderworkspace.Quantity'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='qty_per_train',
            field=models.IntegerField(default=0),
        ),
    ]
