# Generated by Django 3.0 on 2020-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0063_auto_20200731_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoncar',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressonpart',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressontrain',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
