# Generated by Django 3.0 on 2020-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0065_auto_20200731_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressontrain',
            name='progress_on_part',
            field=models.ManyToManyField(to='teamleaderworkspace.ProgressOnPart'),
        ),
    ]
