# Generated by Django 3.0 on 2020-07-31 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0066_auto_20200731_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressonpart',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Train'),
        ),
    ]
