# Generated by Django 3.0 on 2020-08-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0069_auto_20200803_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
