# Generated by Django 3.0 on 2020-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0072_waste_date_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoncar',
            name='up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressonpart',
            name='up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressontrain',
            name='up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
