# Generated by Django 3.0 on 2020-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0074_qualityfeedback_trackingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='code',
            field=models.CharField(max_length=500),
        ),
    ]
