# Generated by Django 3.0 on 2020-08-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0075_auto_20200803_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcode',
            name='package_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingcode',
            name='reference_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.ReferenceApplied'),
        ),
    ]
