# Generated by Django 3.0 on 2020-08-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0076_auto_20200803_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityfeedback',
            name='files',
        ),
        migrations.RemoveField(
            model_name='qualityfeedback',
            name='inspector',
        ),
        migrations.AddField(
            model_name='qualityfeedback',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='qualityfeedback',
            name='reference_to_replace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Reference'),
        ),
        migrations.AddField(
            model_name='qualityfeedback',
            name='replaced_by',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.Tech'),
        ),
        migrations.AlterField(
            model_name='qualityfeedback',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityfeedback',
            name='ncr_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
