# Generated by Django 3.0 on 2020-08-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0077_auto_20200803_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='qualityfeedback',
            old_name='fault',
            new_name='responsible',
        ),
        migrations.AddField(
            model_name='qualityfeedback',
            name='default_type',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.DefaultType'),
        ),
    ]
