# Generated by Django 3.0 on 2020-08-03 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0078_auto_20200803_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityfeedback',
            name='qty_applied',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
