# Generated by Django 3.0 on 2020-08-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0079_qualityfeedback_qty_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='exempt',
            field=models.IntegerField(default=0),
        ),
    ]
