# Generated by Django 3.0 on 2020-09-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0081_auto_20200827_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['teamleader']},
        ),
    ]
