# Generated by Django 3.0 on 2020-09-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0082_auto_20200909_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date_record']},
        ),
    ]
