# Generated by Django 3.0 on 2020-09-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0083_auto_20200909_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_record']},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={'ordering': ['-date_work']},
        ),
    ]
