# Generated by Django 3.0 on 2020-09-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0084_auto_20200909_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={},
        ),
    ]
