# Generated by Django 3.0 on 2020-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0085_auto_20200909_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='location',
            field=models.ManyToManyField(to='teamleaderworkspace.Location'),
        ),
    ]
