# Generated by Django 3.0 on 2020-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0087_auto_20200915_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='image',
            field=models.ImageField(default='train.png', upload_to='reference_pics'),
        ),
    ]
