# Generated by Django 3.0 on 2020-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0088_stockhistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='reference',
            name='image',
            field=models.ImageField(default='train.png', upload_to='reference_pics'),
        ),
    ]
