# Generated by Django 3.0 on 2020-09-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0092_auto_20200915_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workbytech',
            options={'ordering': ['id']},
        ),
    ]
