# Generated by Django 3.0 on 2020-09-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0093_auto_20200915_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-train']},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='workbytech',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={'ordering': ['-id']},
        ),
    ]
