# Generated by Django 3.0 on 2020-09-15 23:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamleaderworkspace', '0095_auto_20200916_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_number', models.CharField(blank=True, max_length=200, null=True)),
                ('replacement', models.BooleanField(default=False)),
                ('qty_applied', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_record', models.DateField()),
                ('last_update', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='pending.png', upload_to='quality_pics')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Car')),
                ('default_type', models.ManyToManyField(blank=True, to='teamleaderworkspace.DefaultType')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Location')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Part')),
                ('reference_to_replace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Reference')),
                ('replaced_by', models.ManyToManyField(blank=True, to='teamleaderworkspace.Tech')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('situation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.SituationNCR')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracking_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.TrackingCode')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Train')),
            ],
        ),
        migrations.DeleteModel(
            name='QualityFeedback',
        ),
    ]
