# Generated by Django 3.0 on 2020-09-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0096_auto_20200916_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultType',
        ),
        migrations.AlterField(
            model_name='quality',
            name='default_type',
            field=models.ManyToManyField(blank=True, to='teamleaderworkspace.WasteCategory'),
        ),
    ]
