# Generated by Django 3.0 on 2020-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0097_auto_20200916_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='date_replacement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
