# Generated by Django 3.0 on 2020-09-16 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0098_quality_date_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='date_replacement',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='replaced_by',
            field=models.ManyToManyField(blank=True, default=None, to='teamleaderworkspace.Tech'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
