# Generated by Django 3.0 on 2020-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0099_auto_20200916_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='qty_applied',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
