# Generated by Django 3.0 on 2020-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0100_auto_20200916_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='image',
        ),
        migrations.AddField(
            model_name='situationncr',
            name='image',
            field=models.ImageField(default='pending.png', upload_to='quality_pics'),
        ),
    ]
