# Generated by Django 3.0 on 2020-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0101_auto_20200916_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='had_stock_update',
            field=models.BooleanField(default=False),
        ),
    ]
