# Generated by Django 3.0 on 2020-09-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0103_auto_20200916_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='pending.png', upload_to='quality_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='situationncr',
            name='image',
        ),
        migrations.AddField(
            model_name='quality',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.ProgressNCR'),
        ),
    ]
