# Generated by Django 3.0 on 2020-09-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
        ('teamleaderworkspace', '0105_remove_quality_qty_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='ncr_responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
