# Generated by Django 3.0 on 2020-09-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamleaderworkspace', '0106_waste_ncr_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamleaderworkspace.Waste'),
        ),
    ]
